### ISSUE TITLE
Strong-named assembly

### ISSUE THREAD

**Issue by erikvdv1** [andrewlock/NetEscapades.Extensions.Logging#1]
First of all, very nice logging library!

The assembly on NuGet is currently not [strong-named](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies). This makes the assembly not suitable for applications which are strong-named themselves.

It would be very helpful if you can release a new version to NuGet with a strong-name?

**Comment by andrewlock** [comment]
Thanks, I've never used (or needed strong-naming) and AFAIK it's generally discouraged by a lot of library authors:

https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/
https://jeremydmiller.com/2014/04/28/fubumvc-lessons-learned-strong-naming-woes-and-workarounds/

I confess I avoid Strong Naming like the plague, more because I don't know much about it and I've seen cleverer people than me fighting it for hours. 

Thata's not to say I _won't_ add it, just that I'll need some convincing 😉

**Comment by erikvdv1** [comment]
I didn't know about the controverse around strong naming. Seems like there are some good reasons not to do it. Even the core-team themselves [don't recommend](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md) it. Thanks!
