### ISSUE TITLE
.log instead of .txt

### ISSUE THREAD

**Issue by ranouf** [andrewlock/NetEscapades.Extensions.Logging#9]
hi,

Thanks for your useful library. I would like to know if it s possible to have the option to specify the extension of the generated file?

thanks

**Comment by andrewlock** [comment]
Hi, the reason it doesn't currently is because the code is largely copied from the [AzureAppServices logger](https://github.com/aspnet/Extensions/blob/master/src/Logging/Logging.AzureAppServices/src/FileLoggerProvider.cs).

Despite that, adding a file extension option seems very reasonable. I'm always open to PRs if you'd like to implement it sooner rather than later 🙂

**Comment by ranouf** [comment]
I will see if I can do that, but probably not now :)
Thanks

**Comment by BrendanCosman** [comment]
I've created a branch here: https://github.com/andrewlock/NetEscapades.Extensions.Logging/pull/13 that will hopefully assist.

**Comment by andrewlock** [comment]
Thanks @BrendanCosman for adding this feature! I've just pushed a new version with the feature to NuGet, so should show up in your feed soon
